dist: focal

language: minimal

before_install:
  - sudo add-apt-repository ppa:neovim-ppa/stable -y
  - sudo apt-get update
  - sudo apt-get -y install neovim

install:
  - git clone --depth=1 https://github.com/leafOfTree/test ../test

  - git clone https://github.com/digitaltoad/vim-pug ../vim-pug --depth=1
  - git clone https://github.com/kchmck/vim-coffee-script ../vim-coffee-script --depth=1
  - git clone https://github.com/leafgarland/typescript-vim ../typescript-vim --depth=1

script:
  - bash ../test/start.sh svelte vim-svelte-plugin
